/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego.de.dados;

/**
 *
 * @author labing506
 */
public class Ventana extends javax.swing.JFrame {
    
    
    
    Dado dado1 =new Dado();
    Dado dado2= new Dado();
    Jugador jugador1 = new Jugador();
    int suma;
    double apuesta;
    
    

    /**
     * Creates new form ventana
     */
    public Ventana() {
        initComponents();
        
        
        txtbilletera.setText(Double.toString(jugador1.billetera));  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnlanzar = new javax.swing.JButton();
        txtnum1 = new javax.swing.JTextField();
        txtnum2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MENSAJE = new javax.swing.JLabel();
        txtapuesta = new javax.swing.JTextField();
        txtbilletera = new javax.swing.JTextField();
        txtmensaje = new javax.swing.JTextField();
        lbsuma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("juego de dados");
        setLocation(new java.awt.Point(700, 300));

        btnlanzar.setBackground(new java.awt.Color(0, 204, 204));
        btnlanzar.setText("LANZAR");
        btnlanzar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnlanzarStateChanged(evt);
            }
        });
        btnlanzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlanzarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlanzarMouseExited(evt);
            }
        });

        txtnum1.setBackground(new java.awt.Color(240, 240, 240));
        txtnum1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        txtnum1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnum1.setText("buena");
        txtnum1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        txtnum1.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        txtnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnum1ActionPerformed(evt);
            }
        });

        txtnum2.setBackground(new java.awt.Color(240, 240, 240));
        txtnum2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        txtnum2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnum2.setText("suerte");
        txtnum2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        txtnum2.setSelectedTextColor(new java.awt.Color(0, 102, 102));

        jLabel1.setText("APUESTA:");

        jLabel2.setText("BILLETERA:");

        MENSAJE.setText("MENSAJE:");

        txtapuesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtapuestaMouseClicked(evt);
            }
        });

        lbsuma.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        lbsuma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnlanzar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbsuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(txtnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(MENSAJE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtapuesta)
                            .addComponent(txtmensaje)
                            .addComponent(txtbilletera))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnum1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(txtnum2))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnlanzar)
                        .addGap(18, 18, 18)
                        .addComponent(lbsuma, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtapuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtbilletera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MENSAJE)
                    .addComponent(txtmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnum1ActionPerformed

    private void btnlanzarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlanzarMouseClicked
        dado1.lanzar();
        dado2.lanzar();
        
        txtnum1.setText(Integer.toString(dado1.valor));
        txtnum2.setText(Integer.toString(dado2.valor));
        
        
        
        suma = dado1.valor + dado2.valor;
        lbsuma.setText(Integer.toString(suma));
        
        apuesta =Integer.parseInt(txtapuesta.getText());
       
        switch(suma){
            
            case 2:{
            txtmensaje.setText("perdiste lo apostado");
            jugador1.billetera=jugador1.billetera- apuesta;
            txtbilletera.setText(Double.toString(jugador1.billetera));
            
            }break;
            case 3:{
            txtmensaje.setText("perdiste el doble de lo apostado");
            jugador1.billetera=jugador1.billetera- (apuesta*2);
            txtbilletera.setText(Double.toString(jugador1.billetera));  
            
               
            }break;
            case 7:{
            txtmensaje.setText("ganaste el doble de lo apostado");
            jugador1.billetera=jugador1.billetera+ (apuesta*2);
            txtbilletera.setText(Double.toString(jugador1.billetera));
                
            
            }break;
            case 11:{
                txtmensaje.setText("ni ganas ni pierdes");
                txtbilletera.setText(Double.toString(jugador1.billetera));
            }break;
            case 12:{
            txtmensaje.setText("ganaste lo apostado");
            jugador1.billetera=jugador1.billetera+ apuesta;
            txtbilletera.setText(Double.toString(jugador1.billetera));
                
            }break;
            case 10:{
            txtmensaje.setText("pierdes todo");
            jugador1.billetera=0;
            txtbilletera.setText(Double.toString(jugador1.billetera));
            }break;
            default:{
                txtmensaje.setText("pierdes el 1.5 de lo aostado");
            jugador1.billetera=jugador1.billetera- (apuesta*1.5);
            txtbilletera.setText(Double.toString(jugador1.billetera));
                
            }
        }
        

    }//GEN-LAST:event_btnlanzarMouseClicked

    private void btnlanzarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlanzarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlanzarMouseExited

    private void btnlanzarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnlanzarStateChanged
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnlanzarStateChanged

    private void txtapuestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtapuestaMouseClicked
        // TODO add your handling code here:
        txtapuesta.setText(null);
    }//GEN-LAST:event_txtapuestaMouseClicked
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new Ventana().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MENSAJE;
    private javax.swing.JButton btnlanzar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbsuma;
    private javax.swing.JTextField txtapuesta;
    private javax.swing.JTextField txtbilletera;
    private javax.swing.JTextField txtmensaje;
    private javax.swing.JTextField txtnum1;
    private javax.swing.JTextField txtnum2;
    // End of variables declaration//GEN-END:variables
}
